#include <iostream>
#include <stdlib.h>
#include "arithmetic_mean.h"

using std::cin;
using std::cout;
using std::endl;

/*
Atividade:
    Escreva um programa que calcula a média aritmética de 3 números inteiros 
    fornecidos pelo usuário. 
*/

int main(int argc, char *argv[]){

    /*
    float inputNumber1;
    float inputNumber2;
    float inputNumber3;
    */

    // Getting user data
    cout << "Arithmetic Mean calculator!" << endl;

    /*
    cout << "Enter the first number: " << endl; 
    cin >> inputNumber1;
    cout << "Enter the second number: " << endl;
    cin >> inputNumber2;
    cout << "Enter the third number: " << endl;
    cin >> inputNumber3;
    */

   /*
   inputNumber1 = atoi(argv[1]);
   inputNumber2 = atoi(argv[2]);
   inputNumber3 = atoi(argv[3]);
   */

    // Result generated by the function arithmeticMean
    float result = arithmeticMean(argc, argv);

    // Output
    cout << "The result is: " << result << endl;
    cout << "END" << endl;
    
    return 0;
}